// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSgYQOewvscfGOtw-rztTWxK1tv3J_YQM',
    appId: '1:192851965709:web:6f8e3881434bef700a6244',
    messagingSenderId: '192851965709',
    projectId: 'scrapy-7e02a',
    authDomain: 'scrapy-7e02a.firebaseapp.com',
    storageBucket: 'scrapy-7e02a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_NwazjkBsZUKP_YLtpgCHs1oF_-iVYg',
    appId: '1:192851965709:android:1ac6a197b0dfeaaa0a6244',
    messagingSenderId: '192851965709',
    projectId: 'scrapy-7e02a',
    storageBucket: 'scrapy-7e02a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0cF0qVUVDYgwTvauxyIsmHIqEgIk1Rvk',
    appId: '1:192851965709:ios:3f24fb70f55905370a6244',
    messagingSenderId: '192851965709',
    projectId: 'scrapy-7e02a',
    storageBucket: 'scrapy-7e02a.appspot.com',
    iosBundleId: 'com.example.flutter_application_1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0cF0qVUVDYgwTvauxyIsmHIqEgIk1Rvk',
    appId: '1:192851965709:ios:42afa8cd8af75d470a6244',
    messagingSenderId: '192851965709',
    projectId: 'scrapy-7e02a',
    storageBucket: 'scrapy-7e02a.appspot.com',
    iosBundleId: 'com.example.flutter_application_1.RunnerTests',
  );
}
